/*
 * Copyright 2014-2016 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define KAA_BUILD_VERSION             "0.10.0"
# define KAA_BUILD_COMMIT_HASH         ""

# define KAA_SDK_TOKEN                 "Ik72lyuZez-SN9kj27tOAn9qsBc"

# define KAA_PROFILE_SCHEMA_VERSION    0

# define DEFAULT_USER_VERIFIER_TOKEN    "75573328582256784833"

# define KAA_SYNC_TIMEOUT               60000L


/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x929a2016,
            320,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -60 , -6 , 51 , -102 , 126 , -24 , -24 , 33 , 10 , 51 , -6 , 40 , 112 , 18 , 53 , 115 , 43 , -72 , -11 , 58 , -47 , 83 , 84 , 31 , 15 , -78 , 119 , -79 , 115 , -52 , -33 , -93 , 75 , -101 , 95 , -1 , 98 , 125 , 0 , -2 , -91 , 103 , 87 , -71 , -14 , -40 , 102 , -49 , -63 , -128 , -93 , -113 , -115 , -92 , 83 , -128 , 92 , 51 , -87 , -37 , -121 , -123 , 82 , -51 , 56 , -110 , 30 , 20 , 111 , -47 , -38 , -57 , 37 , -29 , 12 , 49 , 22 , -111 , 2 , 92 , -122 , -62 , -41 , 28 , -77 , 109 , 58 , 32 , -86 , -58 , -19 , 36 , 61 , -118 , 75 , 98 , 65 , -96 , -68 , -30 , -66 , -98 , -71 , -120 , 56 , -81 , 14 , 114 , 64 , -41 , -58 , 72 , 87 , 23 , 33 , -122 , -21 , 23 , 117 , 49 , 50 , -20 , 20 , -122 , -18 , 3 , 43 , -36 , 87 , -64 , 4 , 22 , 23 , 52 , -77 , 25 , -84 , 41 , 11 , 31 , -51 , -2 , 125 , 91 , 32 , -29 , 113 , -82 , -33 , -36 , 45 , -57 , 63 , -18 , -82 , 8 , -6 , 51 , 37 , 3 , 18 , -46 , 59 , 0 , 56 , 101 , -102 , 52 , 44 , -89 , 99 , -27 , -6 , 28 , 98 , -51 , 44 , -30 , -92 , 63 , -86 , 54 , -94 , -68 , -110 , -95 , 62 , -29 , -29 , -49 , 123 , -68 , -88 , -55 , -63 , -14 , 68 , 120 , -20 , 57 , 74 , 63 , -88 , -107 , -90 , 54 , -121 , 121 , -24 , 49 , 6 , -117 , -74 , 27 , -11 , -72 , -102 , 97 , 13 , -23 , -28 , 60 , -63 , 37 , 42 , -110 , 4 , -67 , -15 , -89 , -66 , -36 , -22 , -55 , 47 , -31 , -97 , 15 , 57 , -51 , 84 , -110 , -33 , -5 , 33 , 35 , 9 , -68 , 36 , 13 , -43 , 33 , -56 , -47 , -71 , 121 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 14 , 50 , 50 , 50 , 46 , 49 , 49 , 50 , 46 , 49 , 48 , 55 , 46 , 52 , 54 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x929a2016,
            320,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -60 , -6 , 51 , -102 , 126 , -24 , -24 , 33 , 10 , 51 , -6 , 40 , 112 , 18 , 53 , 115 , 43 , -72 , -11 , 58 , -47 , 83 , 84 , 31 , 15 , -78 , 119 , -79 , 115 , -52 , -33 , -93 , 75 , -101 , 95 , -1 , 98 , 125 , 0 , -2 , -91 , 103 , 87 , -71 , -14 , -40 , 102 , -49 , -63 , -128 , -93 , -113 , -115 , -92 , 83 , -128 , 92 , 51 , -87 , -37 , -121 , -123 , 82 , -51 , 56 , -110 , 30 , 20 , 111 , -47 , -38 , -57 , 37 , -29 , 12 , 49 , 22 , -111 , 2 , 92 , -122 , -62 , -41 , 28 , -77 , 109 , 58 , 32 , -86 , -58 , -19 , 36 , 61 , -118 , 75 , 98 , 65 , -96 , -68 , -30 , -66 , -98 , -71 , -120 , 56 , -81 , 14 , 114 , 64 , -41 , -58 , 72 , 87 , 23 , 33 , -122 , -21 , 23 , 117 , 49 , 50 , -20 , 20 , -122 , -18 , 3 , 43 , -36 , 87 , -64 , 4 , 22 , 23 , 52 , -77 , 25 , -84 , 41 , 11 , 31 , -51 , -2 , 125 , 91 , 32 , -29 , 113 , -82 , -33 , -36 , 45 , -57 , 63 , -18 , -82 , 8 , -6 , 51 , 37 , 3 , 18 , -46 , 59 , 0 , 56 , 101 , -102 , 52 , 44 , -89 , 99 , -27 , -6 , 28 , 98 , -51 , 44 , -30 , -92 , 63 , -86 , 54 , -94 , -68 , -110 , -95 , 62 , -29 , -29 , -49 , 123 , -68 , -88 , -55 , -63 , -14 , 68 , 120 , -20 , 57 , 74 , 63 , -88 , -107 , -90 , 54 , -121 , 121 , -24 , 49 , 6 , -117 , -74 , 27 , -11 , -72 , -102 , 97 , 13 , -23 , -28 , 60 , -63 , 37 , 42 , -110 , 4 , -67 , -15 , -89 , -66 , -36 , -22 , -55 , 47 , -31 , -97 , 15 , 57 , -51 , 84 , -110 , -33 , -5 , 33 , 35 , 9 , -68 , 36 , 13 , -43 , 33 , -56 , -47 , -71 , 121 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 14 , 50 , 50 , 50 , 46 , 49 , 49 , 50 , 46 , 49 , 48 , 55 , 46 , 52 , 54 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    1

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
2 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

